site_name: Laboratorio de Electrónica
site_description: Laboratorio de Electrónica Básica
site_author: Juan Echevarría
site_url: https://lab-electronica.github.io/electronica-basica

repo_url: https://github.com/lab-electronica/electronica-basica
repo_name: GitHub

copyright: >
  © 2026 Juan Echevarría —
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.es" target="_blank">CC BY-NC-SA 4.0</a>

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: es
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/[tu-organizacion]
